# Generated by Django 3.2.6 on 2021-08-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20210818_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='front_page',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='isbn10',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='isbn13',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='pages',
            field=models.IntegerField(null=True),
        ),
    ]
