# Generated by Django 3.2.6 on 2021-08-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20210818_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
