# Generated by Django 3.2.6 on 2021-08-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_catalogue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='front_page',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
