# Generated by Django 3.2.6 on 2021-08-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_alter_catalogue_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='isbn10',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='isbn13',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
