# Generated by Django 3.2.6 on 2021-08-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_alter_catalogue_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='front_page',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='isbn10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='isbn13',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='published_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
