# Generated by Django 3.2.6 on 2021-08-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20210822_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
