# Generated by Django 3.2.6 on 2021-08-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20210825_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='industry_identifiers',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
